### ISSUE TITLE
Rechazado.

### ISSUE THREAD

**Issue by t0kyolover** [4GeeksAcademy/Contact-List-App-React-Context-Guillermo#1]
- [x] Resolver

![Screenshot 2024-06-16 at 15 05 38](https://github.com/4GeeksAcademy/Contact-List-App-React-Context-Guillermo/assets/144109471/c6e4c566-d8ce-4b07-9e04-6b3eb712aae3)

**Comment by GuilleMarejada** [comment]
Todos los errores solo pasan en codespace, en local 0 problemas, he actualizado el import del navbar que tambien daba solo problemas en el codespace, pero el resto de errores no me pasan en local y no tengo ni idea... aun así después de arreglar el import funciona bien aunque se vean todos esos errores.

**Comment by t0kyolover** [comment]
Esta parte hay que tener en cuenta cuando trabajas en el local, la idea es programar de tal manera para que se pueda ejecutar siempre, independientemente de donde
